import { useState } from 'react';
import { Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { router, type Href } from 'expo-router';
import { Button, PetPortrait, PetSelector, Screen, useSectionColors } from '../../components/ui';
import { AdoptionPhoto } from '../../components/adoption-photo';
import { BrandIcon, ScriptLine, fonts } from '../../components/brand';
import { adoptionListings } from '../../core/model';
import { useApp } from '../../state/app-state';
export default function Home() {
  const { pet, accountMode, mode } = useApp(); const colors = useSectionColors(); const [switchOpen, setSwitchOpen] = useState(false);
  const tags = accountMode ? [] : pet.species === 'Kedi' ? ['Meraklı · örnek', 'Sosyal · örnek'] : ['Neşeli · örnek', 'Sosyal · örnek'];
  const actions: { title: string; label: string; icon: 'person' | 'heart' | 'home'; href: Href }[] = [
    { title: 'Dostum', label: 'Profili ve dijital kimliği aç', icon: 'person', href: '/profile' },
    { title: 'Tanış', label: 'PatiMatch keşfi', icon: 'heart', href: '/match' },
    { title: 'Yuva ol', label: 'Sahiplendirme ilanları', icon: 'home', href: '/adoption' },
  ];
  return <Screen title="PetID" tab headerRight={<Pressable accessibilityRole="button" accessibilityLabel="Hayvan değiştir" onPress={() => setSwitchOpen(true)} style={{ width: 48, height: 48, borderRadius: 24, backgroundColor: colors.purpleSoft, alignItems: 'center', justifyContent: 'center' }}><PetPortrait key={pet.id + pet.photos[0]} size={34}/></Pressable>}>
    <Pressable testID="home-pet-hero" accessibilityRole="button" accessibilityLabel={pet.name + ' profilini aç'} onPress={() => router.push('/profile')} style={{ minHeight: 128, padding: 12, borderRadius: 22, backgroundColor: colors.purpleSoft, borderWidth: 1, borderColor: '#E7DEF7', flexDirection: 'row', alignItems: 'center', gap: 12 }}>
      <View style={{ width: 88, alignItems: 'center', gap: 2 }}><PetPortrait key={pet.id + pet.photos[0]} size={78}/>{!pet.photos.length ? <Text style={{ color: colors.accent, fontFamily: fonts.strong, fontSize: 10 }}>Fotoğraf ekle ›</Text> : null}</View>
      <View style={{ flex: 1, gap: 4 }}><Text numberOfLines={1} style={{ color: colors.text, fontFamily: fonts.display, fontSize: 24 }}>{pet.name}</Text><Text numberOfLines={1} style={{ color: colors.text, fontFamily: fonts.body, fontSize: 12 }}>{pet.age} · {pet.species}</Text><View style={{ gap: 3 }}>{tags.map(tag => <Text key={tag} numberOfLines={1} style={{ color: mode === 'dark' ? '#9BECC9' : colors.greenDark, fontFamily: fonts.strong, fontSize: 10 }}>{tag}</Text>)}</View></View>
      <View style={{ width: 66, alignItems: 'flex-end', gap: 6 }}><ScriptLine color={colors.text} size={15}>İyi kal, mutlu kal</ScriptLine><BrandIcon name="chevron" color={colors.accent} size={17}/></View>
    </Pressable>
    <View testID="home-three-paths" style={{ flexDirection: 'row', gap: 8 }}>{actions.map(item => <Pressable key={item.title} accessibilityRole="button" accessibilityLabel={item.label} onPress={() => router.push(item.href)} style={{ flex: 1, minHeight: 86, alignItems: 'center', justifyContent: 'center', gap: 5, borderRadius: 18, borderWidth: 1, borderColor: colors.border, backgroundColor: item.href === '/match' ? colors.purpleSoft : colors.surface }}><BrandIcon name={item.icon} size={24} color={item.href === '/match' ? colors.accent : colors.text}/><Text style={{ color: colors.text, fontFamily: fonts.strong, fontSize: 12 }}>{item.title}</Text></Pressable>)}</View>
    <View testID="home-acil-pati" style={{ borderRadius: 22, backgroundColor: '#FFF0EC', borderWidth: 1, borderColor: '#F7D8D1', padding: 14, gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 7 }}><BrandIcon name="heart" filled size={21} color="#E46067"/><Text accessibilityRole="header" style={{ color: '#182033', fontFamily: fonts.display, fontSize: 21 }}>Acil Pati</Text></View><Text style={{ color: '#273153', fontFamily: fonts.body, fontSize: 12 }}>Sokakta yardıma ihtiyacı olan bir pati mi gördün?</Text>
      <Pressable accessibilityRole="button" accessibilityLabel="Yaralı veya kayıp hayvan bildir" onPress={() => router.push({ pathname: '/reports', params: { source: 'street' } })} style={{ minHeight: 48, borderRadius: 14, backgroundColor: '#E46067', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 }}><Text style={{ color: '#FFFFFF', fontFamily: fonts.strong, fontSize: 13 }}>Yaralı / kayıp hayvan bildir</Text></Pressable>
      <Pressable accessibilityRole="button" accessibilityLabel="Yakındaki açık veterineri bul" onPress={() => router.push({ pathname: '/emergency', params: { from: 'home' } })} style={{ minHeight: 48, borderRadius: 14, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8 }}><Text style={{ color: '#273153', fontFamily: fonts.strong, fontSize: 12 }}>Yakındaki açık veterineri bul ›</Text></Pressable>
    </View>
    <View style={{ gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 4 }}><View><Text accessibilityRole="header" style={{ color: colors.text, fontFamily: fonts.display, fontSize: 21 }}>Yeni yuva arayanlar</Text><Text style={{ color: colors.muted, fontFamily: fonts.body, fontSize: 11 }}>Örnek ilanlar</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Tüm sahiplendirme ilanlarını gör" onPress={() => router.push('/adoption')} style={{ minHeight: 48, justifyContent: 'center' }}><Text style={{ color: colors.accent, fontFamily: fonts.strong, fontSize: 12 }}>Tümünü gör ›</Text></Pressable></View>
      <ScrollView testID="home-adoption-carousel" horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{adoptionListings.slice(0, 3).map(listing => <Pressable key={listing.id} accessibilityRole="button" accessibilityLabel={listing.name + ' örnek ilan detayını aç'} onPress={() => router.push({ pathname: '/adoption/[id]', params: { id: listing.id } })} style={{ width: 250, minHeight: 102, borderRadius: 18, padding: 8, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: 9 }}><AdoptionPhoto listing={listing} size={84}/><View style={{ flex: 1, gap: 3 }}><Text numberOfLines={1} style={{ color: colors.text, fontFamily: fonts.strong, fontSize: 15 }}>{listing.name}</Text><Text numberOfLines={1} style={{ color: colors.muted, fontFamily: fonts.body, fontSize: 11 }}>{listing.species} · {listing.age}</Text><Text numberOfLines={1} style={{ color: colors.muted, fontFamily: fonts.body, fontSize: 10 }}>{listing.city} · örnek</Text><Text numberOfLines={1} style={{ color: colors.text, fontFamily: fonts.body, fontSize: 11 }}>{listing.teaser}</Text></View></Pressable>)}</ScrollView>
    </View>
    <Modal visible={switchOpen} onRequestClose={() => setSwitchOpen(false)}><Screen title="Dostunu seç"><Button label="Seçimi kapat" secondary onPress={() => setSwitchOpen(false)}/><PetSelector/></Screen></Modal>
  </Screen>;
}
