import { router, type Href } from 'expo-router';
import { useState } from 'react';
import { Image, Modal, Pressable, Text, View } from 'react-native';
import { Button, Screen, Card, Label, Note, Paw, Segments, useSectionColors } from '../../components/ui';
import { serviceCategories, servicesDemo, type DemoService } from '../../data/services-demo';
export default function Services() {
  const colors = useSectionColors('services'); const [category, setCategory] = useState('Tümü');
  const [favorites, setFavorites] = useState<string[]>([]); const [selected, setSelected] = useState<DemoService | null>(null);
  return <Screen title="Hizmetler" tab tone="services"><Segments testID="service-categories" labels={[...serviceCategories]} selected={category} onSelect={setCategory} />
    <View testID="services-grid" style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>{servicesDemo.filter(item => category === 'Tümü' || item.category === category).map(item => <View key={item.id} style={{ width: '48%', borderRadius: 22, overflow: 'hidden', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border }}><Pressable accessibilityRole="button" accessibilityLabel={item.name + ' detayını aç'} onPress={() => setSelected(item)}><View style={{ aspectRatio: .98, backgroundColor: colors.greenSoft }}><Image accessibilityLabel={item.name + ' temsili hizmet görseli'} source={item.photo} style={{ width: '100%', height: '100%' }} /><View style={{ position: 'absolute', left: 8, bottom: 8, right: 8 }}><Text numberOfLines={1} style={{ alignSelf: 'flex-start', paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, backgroundColor: '#FFFFFFF0', color: '#182033', fontSize: 10, fontWeight: '600' }}>{item.category}</Text></View></View><View style={{ padding: 12, gap: 6 }}><Text numberOfLines={2} style={{ color: colors.text, fontWeight: '700', fontSize: 16 }}>{item.name}</Text><Text numberOfLines={2} style={{ color: colors.muted, fontSize: 11 }}>★ {item.rating} ({item.reviews}) · {item.distance}</Text><Text numberOfLines={2} style={{ color: colors.muted, fontSize: 12, lineHeight: 17 }}>{item.description}</Text></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={item.name + ' favori'} accessibilityState={{ selected: favorites.includes(item.id) }} onPress={() => setFavorites(rows => rows.includes(item.id) ? rows.filter(id => id !== item.id) : [...rows, item.id])} style={{ position: 'absolute', right: 4, top: 4, width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }}><Text style={{ width: 32, height: 32, textAlign: 'center', lineHeight: 32, borderRadius: 16, backgroundColor: '#FFFFFFEB', fontSize: 23, color: favorites.includes(item.id) ? '#F43F5E' : '#182033' }}>{favorites.includes(item.id) ? '♥' : '♡'}</Text></Pressable></View>)}</View>
    <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10, paddingTop: 12 }}><Paw size={20} /><Label heading>Topluluk ve yardım</Label></View><View style={{ gap: 8 }}>{[{ label: 'Sahiplendirme', href: '/adoption' }, { label: 'Kayıp / yaralı ilanları', href: '/reports' }, { label: 'Acil veteriner', href: '/emergency' }].map(link => <Pressable key={link.href} accessibilityRole="button" accessibilityLabel={link.label} onPress={() => router.push(link.href as Href)} style={{ minHeight: 48, borderRadius: 14, backgroundColor: colors.surface, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Text style={{ color: colors.text, fontSize: 14 }}>{link.label}</Text><Text style={{ color: colors.muted }}>↗</Text></Pressable>)}</View><Modal visible={!!selected} onRequestClose={() => setSelected(null)}><Screen title={selected?.name ?? 'Hizmet'} tone="services"><Button label="Hizmet detayını kapat" secondary onPress={() => setSelected(null)} />{selected ? <><Image source={selected.photo} style={{ width: '100%', aspectRatio: 1.2, borderRadius: 24 }} /><Label heading>{selected.category}</Label><Note>{selected.description}</Note><Card><Label>Örnek hizmet profili</Label><Note>İşletme, puanlar ve mesafe kurgu veridir. Rezervasyon, ödeme veya gerçek işletme bağlantısı bulunmaz.</Note></Card></> : null}</Screen></Modal></Screen>;
}
