import { router, type Href } from 'expo-router';
import { useState } from 'react';
import { Image, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { Button, Screen, Card, Label, Note, Field, useSectionColors } from '../../components/ui';
import { BrandIcon, ScriptLine, fonts } from '../../components/brand';
import { serviceCategories, servicesDemo, serviceLocation, type DemoService } from '../../data/services-demo';
import { nativeServices } from '../../services/native';
import { resultMessage } from '../../core/services';
const displayCategory = (value: string) => value === 'Pet Kuaförü' ? 'Kuaför' : value === 'Pet Oteli' ? 'Otel' : value;
const matchesCategory = (selected: string, item: DemoService) => selected === 'Tümü' || displayCategory(item.category) === selected;
export default function Services() {
  const colors = useSectionColors('services'); const [category, setCategory] = useState('Tümü'); const [favorites, setFavorites] = useState<string[]>([]); const [selected, setSelected] = useState<DemoService | null>(null);
  const [searchOpen, setSearchOpen] = useState(false); const [query, setQuery] = useState(''); const [locationOpen, setLocationOpen] = useState(false); const [locationLabel, setLocationLabel] = useState(serviceLocation.city); const [locationNotice, setLocationNotice] = useState('');
  const rows = servicesDemo.filter(item => matchesCategory(category,item) && (!query.trim() || (item.name + ' ' + item.category + ' ' + item.description).toLocaleLowerCase('tr').includes(query.trim().toLocaleLowerCase('tr'))));
  async function chooseCurrentLocation() {
    const result = await nativeServices.locate(); if(result.status === 'success') { setLocationLabel('Konumum'); setLocationNotice('Cihaz konumu alındı. Hizmet ve mesafe değerleri hâlâ örnek veridir.'); setLocationOpen(false); } else setLocationNotice(resultMessage(result));
  }
  return <Screen title="Hizmetler" tab tone="services" headerRight={<View style={{ flexDirection: 'row', alignItems: 'center', gap: 4 }}><Pressable accessibilityRole="button" accessibilityLabel="Konum seç" onPress={() => setLocationOpen(true)} style={{ minHeight: 48, flexDirection: 'row', alignItems: 'center', gap: 2 }}><BrandIcon name="pin" color={colors.text} size={17}/><Text numberOfLines={1} style={{ color: colors.text, fontFamily: fonts.body, fontSize: 11, maxWidth: 74 }}>{locationLabel}</Text><BrandIcon name="chevron" color={colors.text} size={12}/></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Hizmet ara" onPress={() => setSearchOpen(value => !value)} style={{ width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }}><BrandIcon name="search" color={colors.text} size={21}/></Pressable></View>}>
    <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 }}><View style={{ flexDirection: 'row', alignItems: 'center', gap: 8 }}><BrandIcon name="briefcase" size={24} color={colors.text}/><Text accessibilityRole="header" style={{ color: colors.text, fontFamily: fonts.display, fontSize: 25 }}>Hizmetler</Text></View><View style={{ maxWidth: 116 }}><ScriptLine color={colors.text} size={17}>Mutlu patiler, güvenilir insanlar.</ScriptLine></View></View>
    {searchOpen ? <Field label="Hizmet ara" value={query} onChangeText={setQuery} placeholder="İsim veya kategori"/> : null}
    <ScrollView testID="service-categories" horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 6, paddingVertical: 2 }}>
      {serviceCategories.map(label => <Pressable key={label} accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ selected: label === category }} onPress={() => setCategory(label)} style={{ minHeight: 48, paddingHorizontal: 8, borderRadius: 17, backgroundColor: label === category ? colors.accent : colors.purpleSoft, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: label === category ? '#FFFFFF' : colors.text, fontFamily: fonts.strong, fontSize: 11 }}>{label}</Text></Pressable>)}
    </ScrollView>
    <View testID="services-grid" style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 10 }}>{rows.map(item => <View key={item.id} style={{ width: '48%', borderRadius: 18, overflow: 'hidden', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, boxShadow: [{ offsetX: 0, offsetY: 3, blurRadius: 12, color: colors.shadow + '10' }] }}><Pressable accessibilityRole="button" accessibilityLabel={item.name + ' detayını aç'} onPress={() => setSelected(item)}><View style={{ aspectRatio: .78, backgroundColor: colors.purpleSoft }}><Image accessibilityLabel={item.name + ' temsili hizmet görseli'} source={item.photo} resizeMode="cover" style={{ width: '100%', height: '100%' }}/><View style={{ position: 'absolute', left: 8, bottom: 8 }}><Text style={{ color: '#5741A8', backgroundColor: '#FFFFFFF2', borderRadius: 9, overflow: 'hidden', fontFamily: fonts.strong, fontSize: 10, paddingHorizontal: 7, paddingVertical: 4 }}>{displayCategory(item.category)}</Text></View></View><View style={{ padding: 10, gap: 6 }}><Text numberOfLines={1} adjustsFontSizeToFit style={{ color: colors.text, fontFamily: fonts.strong, fontSize: 14 }}>{item.name}</Text><View style={{ flexDirection: 'row', alignItems: 'center', gap: 3 }}><BrandIcon name="star" color="#F5A623" size={13}/><Text numberOfLines={1} style={{ color: colors.text, fontFamily: fonts.body, fontSize: 10, flexShrink: 1 }}>{item.rating} ({item.reviews})</Text><BrandIcon name="pin" color={colors.muted} size={11}/><Text numberOfLines={1} style={{ color: colors.text, fontFamily: fonts.body, fontSize: 10 }}>{item.distance}</Text></View><Text numberOfLines={2} style={{ color: colors.text, fontFamily: fonts.body, fontSize: 11, lineHeight: 16 }}>{item.description}</Text></View></Pressable><Pressable accessibilityRole="button" accessibilityLabel={item.name + ' favori'} accessibilityState={{ selected: favorites.includes(item.id) }} onPress={() => setFavorites(values => values.includes(item.id) ? values.filter(id => id !== item.id) : [...values,item.id])} style={{ position: 'absolute', right: 2, top: 2, width: 48, height: 48, alignItems: 'center', justifyContent: 'center' }}><View style={{ width: 30, height: 30, borderRadius: 15, backgroundColor: '#18203366', alignItems: 'center', justifyContent: 'center' }}><BrandIcon name="heart" color={favorites.includes(item.id) ? '#F43F5E' : '#FFFFFF'} size={20} filled={favorites.includes(item.id)}/></View></Pressable></View>)}</View>
    {!rows.length ? <Note>Bu aramaya uygun örnek hizmet bulunmadı.</Note> : null}
    <View style={{ gap: 8, paddingTop: 8 }}><Text style={{ color: colors.text, fontFamily: fonts.display, fontSize: 20 }}>Topluluk ve yardım</Text>{[{ label: 'Sahiplendirme', href: '/adoption' }, { label: 'Kayıp / yaralı ilanları', href: '/reports' }, { label: 'Acil veteriner', href: '/emergency' }].map(link => <Pressable key={link.href} accessibilityRole="button" accessibilityLabel={link.label} onPress={() => router.push(link.href as Href)} style={{ minHeight: 48, borderRadius: 16, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Text style={{ color: colors.text, fontFamily: fonts.strong, fontSize: 13 }}>{link.label}</Text><BrandIcon name="chevron" color={colors.accent} size={17}/></Pressable>)}</View>
    <Modal visible={locationOpen} onRequestClose={() => setLocationOpen(false)}><Screen title="Konum seç"><Button label="Konum seçimini kapat" secondary onPress={() => setLocationOpen(false)}/><Card><Label heading>Hizmet bölgesi</Label><Note>Bu ekrandaki işletmeler ve mesafeler örnek veridir.</Note><Button label="İstanbul · örnek" secondary onPress={() => { setLocationLabel(serviceLocation.city); setLocationOpen(false); }}/><Button label="Cihaz konumumu kullan" onPress={() => void chooseCurrentLocation()}/>{locationNotice ? <Note>{locationNotice}</Note> : null}</Card></Screen></Modal>
    <Modal visible={!!selected} onRequestClose={() => setSelected(null)}><Screen title={selected?.name ?? 'Hizmet'} tone="services"><Button label="Hizmet detayını kapat" secondary onPress={() => setSelected(null)}/>{selected ? <><Image source={selected.photo} resizeMode="cover" style={{ width: '100%', aspectRatio: 1.2, borderRadius: 24 }}/><Label heading>{selected.category}</Label><Note>{selected.description}</Note><Card><Label>Örnek hizmet profili</Label><Note>İşletme, puanlar ve mesafe kurgu veridir. Rezervasyon, ödeme veya gerçek işletme bağlantısı bulunmaz.</Note></Card></> : null}</Screen></Modal>
  </Screen>;
}
